// Code generated by protoc-gen-go. DO NOT EDIT.
// source: models/models.proto

package models // import "github.com/mycodesmells/golang-examples/cel/models"

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type Person struct {
	Name                 string   `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Country              string   `protobuf:"bytes,2,opt,name=country,proto3" json:"country,omitempty"`
	Age                  int32    `protobuf:"varint,3,opt,name=age,proto3" json:"age,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Person) Reset()         { *m = Person{} }
func (m *Person) String() string { return proto.CompactTextString(m) }
func (*Person) ProtoMessage()    {}
func (*Person) Descriptor() ([]byte, []int) {
	return fileDescriptor_models_e210868aa8beb649, []int{0}
}
func (m *Person) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Person.Unmarshal(m, b)
}
func (m *Person) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Person.Marshal(b, m, deterministic)
}
func (dst *Person) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Person.Merge(dst, src)
}
func (m *Person) XXX_Size() int {
	return xxx_messageInfo_Person.Size(m)
}
func (m *Person) XXX_DiscardUnknown() {
	xxx_messageInfo_Person.DiscardUnknown(m)
}

var xxx_messageInfo_Person proto.InternalMessageInfo

func (m *Person) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *Person) GetCountry() string {
	if m != nil {
		return m.Country
	}
	return ""
}

func (m *Person) GetAge() int32 {
	if m != nil {
		return m.Age
	}
	return 0
}

type Country struct {
	Code                 string   `protobuf:"bytes,1,opt,name=code,proto3" json:"code,omitempty"`
	BeerLegal            bool     `protobuf:"varint,2,opt,name=beer_legal,json=beerLegal,proto3" json:"beer_legal,omitempty"`
	BeerAgeLimit         int32    `protobuf:"varint,3,opt,name=beer_age_limit,json=beerAgeLimit,proto3" json:"beer_age_limit,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Country) Reset()         { *m = Country{} }
func (m *Country) String() string { return proto.CompactTextString(m) }
func (*Country) ProtoMessage()    {}
func (*Country) Descriptor() ([]byte, []int) {
	return fileDescriptor_models_e210868aa8beb649, []int{1}
}
func (m *Country) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Country.Unmarshal(m, b)
}
func (m *Country) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Country.Marshal(b, m, deterministic)
}
func (dst *Country) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Country.Merge(dst, src)
}
func (m *Country) XXX_Size() int {
	return xxx_messageInfo_Country.Size(m)
}
func (m *Country) XXX_DiscardUnknown() {
	xxx_messageInfo_Country.DiscardUnknown(m)
}

var xxx_messageInfo_Country proto.InternalMessageInfo

func (m *Country) GetCode() string {
	if m != nil {
		return m.Code
	}
	return ""
}

func (m *Country) GetBeerLegal() bool {
	if m != nil {
		return m.BeerLegal
	}
	return false
}

func (m *Country) GetBeerAgeLimit() int32 {
	if m != nil {
		return m.BeerAgeLimit
	}
	return 0
}

func init() {
	proto.RegisterType((*Person)(nil), "mycodesmells.celgo.models.Person")
	proto.RegisterType((*Country)(nil), "mycodesmells.celgo.models.Country")
}

func init() { proto.RegisterFile("models/models.proto", fileDescriptor_models_e210868aa8beb649) }

var fileDescriptor_models_e210868aa8beb649 = []byte{
	// 226 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x4c, 0x90, 0x41, 0x4b, 0x03, 0x31,
	0x10, 0x85, 0x59, 0x5b, 0x5b, 0x3b, 0x88, 0xc8, 0x78, 0x59, 0x0f, 0x42, 0x29, 0x1e, 0x7a, 0x71,
	0x17, 0xd4, 0x3f, 0xa0, 0x5e, 0x3c, 0xf4, 0x20, 0x7b, 0xf4, 0x52, 0xb2, 0xe9, 0x30, 0x2e, 0x4c,
	0x32, 0x25, 0x49, 0xc1, 0xfe, 0x7b, 0x49, 0xba, 0x05, 0x4f, 0x79, 0xf9, 0xde, 0xf0, 0x86, 0x79,
	0x70, 0xe7, 0x74, 0x47, 0x12, 0xdb, 0xd3, 0xd3, 0xec, 0x83, 0x26, 0xc5, 0x7b, 0x77, 0xb4, 0xba,
	0xa3, 0xe8, 0x48, 0x24, 0x36, 0x96, 0x84, 0xb5, 0x39, 0x0d, 0xac, 0x3e, 0x61, 0xf6, 0x45, 0x21,
	0xaa, 0x47, 0x84, 0xa9, 0x37, 0x8e, 0xea, 0x6a, 0x59, 0xad, 0x17, 0x5d, 0xd1, 0x58, 0xc3, 0xdc,
	0xea, 0xc1, 0xa7, 0x70, 0xac, 0x2f, 0x0a, 0x3e, 0x7f, 0xf1, 0x16, 0x26, 0x86, 0xa9, 0x9e, 0x2c,
	0xab, 0xf5, 0x65, 0x97, 0xe5, 0xaa, 0x87, 0xf9, 0xc7, 0x68, 0x22, 0x4c, 0xf3, 0xbe, 0x73, 0x54,
	0xd6, 0xf8, 0x00, 0xd0, 0x13, 0x85, 0xad, 0x10, 0x1b, 0x29, 0x69, 0x57, 0xdd, 0x22, 0x93, 0x4d,
	0x06, 0xf8, 0x08, 0x37, 0xc5, 0x36, 0x4c, 0x5b, 0x19, 0xdc, 0x90, 0xc6, 0xe8, 0xeb, 0x4c, 0xdf,
	0x98, 0x36, 0x99, 0xbd, 0xbf, 0x7e, 0x3f, 0xf3, 0x90, 0x7e, 0x0e, 0x7d, 0x63, 0xd5, 0xb5, 0xff,
	0xaf, 0x6a, 0x59, 0xc5, 0x78, 0x7e, 0xa2, 0x5f, 0xe3, 0xf6, 0x42, 0xb1, 0xb5, 0x24, 0x63, 0x09,
	0xfd, 0xac, 0xb4, 0xf0, 0xf2, 0x17, 0x00, 0x00, 0xff, 0xff, 0x36, 0x6b, 0xb3, 0xb3, 0x1c, 0x01,
	0x00, 0x00,
}
